### PR TITLE
fix: enable scrolling in modals (fixes #23)

### LINKED ISSUE #23: Modal component contents don't scroll
If a modal's content is longer than the page, it gets clipped and there is no vertical scrollbar.  Suggested solution: make the backdrop (the translucent div) the parent of the modal div and give it `overflow-y: auto`.  Would also require `stopPropagation` for clicks on the modal as they would propagate to the parent and close the modal otherwise.  If this solution sounds good I can make a PR. Thanks!

### PR DESCRIPTION
**Pull request by gushogg-blake**
This also fixes clicking the sides of the modal to close.

### CODE REVIEW

**Comment by shinokada** [comment]
Thanks. I'd like to merge it. But when I pull, I get the following error:

> git pull git://github.com/gushogg-blake/flowbite-svelte.git main
> fatal: remote error: 
>   The unauthenticated git protocol on port 9418 is no longer supported.
> Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by shinokada** [comment]
I had to run the following before the PR.

```
git config --global url."git@github.com:".insteadOf git://github.com/ 
git config --global pull.ff only
```

**Comment by shinokada** [comment]
Since your branch is behind the upstream master, can you fetch the latest version of the branch:

```
git checkout your-branch
git pull upstream master
```

Or

```
git checkout your-branch
git pull --rebase upstream master
```

Please let me know.

**Comment by gushogg-blake** [comment]
I've merged latest main now, does that work?

**Comment by shinokada** [comment]
Yep. it worked. I merged it and updated npm to 0.13.3. Thanks again for your great work.

**Pull request merged**
